// ============================================================
// AI dynamic Quiz Question Model
// ============================================================
import mongoose from 'mongoose';

const questionSchema = new mongoose.Schema(
  {
    lessonId: {
      type: String,
      required: true,
    },
    question: {
      type: String,
      required: true,
    },
    options: [
      {
        type: String,
        required: true,
      },
    ],
    answer: {
      type: String,
      required: true,
    },
    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
      default: 'easy',
    },
    tags: [
      {
        type: String,
      },
    ],
    // If true, the question was dynamically generated by AI and stored so others can use too!
    isAIGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model('Question', questionSchema);
